<#-- MapStruct Mapper Template -->
package ${package.mapper};

import ${package.entity}.${entityClass};
import ${package.dto.request}.Create${entityClass}Request;
import ${package.dto.request}.Update${entityClass}Request;
import ${package.dto.response}.${entityClass}Response;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import java.util.List;

/**
 * MapStruct mapper for ${entityClass}
 * Generated by MCP PostgreSQL SDK
 */
@Mapper(componentModel = "spring", 
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface ${entityClass}Mapper {
    
    ${entityClass} toEntity(Create${entityClass}Request request);
    
    ${entityClass}Response toResponse(${entityClass} entity);
    
    List<${entityClass}Response> toResponseList(List<${entityClass}> entities);
    
    void updateEntity(Update${entityClass}Request request, @MappingTarget ${entityClass} entity);
}