<#-- Request DTO Template -->
package ${package.dto.request};

import jakarta.validation.constraints.*;
<#if lombok>
import lombok.Data;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
</#if>
<#list imports as import>
import ${import};
</#list>

/**
 * Request DTO for creating ${entityClass}
 * Generated by MCP PostgreSQL SDK
 */
<#if lombok>
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
</#if>
public class Create${entityClass}Request {
    
<#list fields as field>
<#if !field.primaryKey && !field.isAuditField>
    <#if validation && !field.nullable>
    @NotNull(message = "${field.name} is required")
    </#if>
    <#if validation && field.type == "String" && field.length??>
    @Size(max = ${field.length}, message = "${field.name} must not exceed ${field.length} characters")
    </#if>
    private ${field.type} ${field.name};
    
</#if>
</#list>

<#if !lombok>
    // Getters and Setters
<#list fields as field>
<#if !field.primaryKey && !field.isAuditField>
    public ${field.type} get${field.name?cap_first}() {
        return ${field.name};
    }
    
    public void set${field.name?cap_first}(${field.type} ${field.name}) {
        this.${field.name} = ${field.name};
    }
    
</#if>
</#list>
</#if>
}