<#-- Response DTO Template -->
package ${package.dto.response};

<#if lombok>
import lombok.Data;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
</#if>
<#list imports as import>
import ${import};
</#list>

/**
 * Response DTO for ${entityClass}
 * Generated by MCP PostgreSQL SDK
 */
<#if lombok>
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
</#if>
public class ${entityClass}Response {
    
<#list fields as field>
    private ${field.type} ${field.name};
</#list>

<#if !lombok>
    // Getters and Setters
<#list fields as field>
    public ${field.type} get${field.name?cap_first}() {
        return ${field.name};
    }
    
    public void set${field.name?cap_first}(${field.type} ${field.name}) {
        this.${field.name} = ${field.name};
    }
    
</#list>
</#if>
}