<#-- Index Creation Migration Template -->
-- Indexes for ${tableName} table
-- Generated by MCP PostgreSQL SDK

<#list fields as field>
<#if field.indexed && !field.primaryKey && !field.unique>
CREATE INDEX idx_${tableName}_${field.columnName} ON ${tableName}(${field.columnName});
</#if>
</#list>

<#if hasAuditFields>
-- Audit field indexes
CREATE INDEX idx_${tableName}_created_at ON ${tableName}(created_at);
CREATE INDEX idx_${tableName}_updated_at ON ${tableName}(updated_at);
</#if>

<#if hasSoftDelete>
-- Soft delete index
CREATE INDEX idx_${tableName}_deleted ON ${tableName}(deleted) WHERE deleted = false;
</#if>

<#-- Composite indexes for common query patterns -->
<#if compositeIndexes??>
<#list compositeIndexes as index>
CREATE INDEX idx_${tableName}_${index.name} ON ${tableName}(${index.columns});
</#list>
</#if>